metadata.format.version = "1.1"

[versions]

jetbrains = "24.1.0"
ignite = "1.1.0"
mixin = "0.8.7"
paperweight = "1.7.7"
shadow = "8.1.2"
spotless = "6.23.3"
paper = "1.21.3-R0.1-SNAPSHOT"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }

ignite = { group = "space.vectrix.ignite", name = "ignite-api", version.ref = "ignite" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }

build-paperweight = { module = "io.papermc.paperweight.userdev:io.papermc.paperweight.userdev.gradle.plugin", version.ref = "paperweight" }
build-shadow = { module = "io.github.goooler:shadow", version.ref = "shadow" }
build-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
